version: '3.3'
services:
    web:
        image: robertfreeman/robcoin_gui
        deploy:
            mode: replicated
            replicas: 2
            labels:
              com.docker.lb.hosts: coin.robert.dtcntr.net
              com.docker.lb.port: 80
        networks:
            - coin_ingress
    api:
        image: robertfreeman/tempapi
        deploy:
           labels:
             com.docker.lb.hosts: api.coin.robert.dtcntr.net
             com.docker.lb.port: 8082
        networks:
            - coin_ingress

    hasher:
        image: robertfreeman/robhasher
        deploy:
            mode: replicated
            replicas: 2
        networks:
            - coin_ingress

    redis:
        image: robertfreeman/redis-cont
        networks:
            - coin_ingress

networks:
    coin_ingress:
       driver: overlay
       ipam:
           driver: default
           config:
              - subnet: 172.28.0.0/16
