version: '3.3'
services:
    web:
        image: dtr.r0b.cc/engineering/robcoin_gui:1.0
        deploy:
            mode: replicated
            replicas: 2
            labels:
              com.docker.lb.hosts: coin.r0b.cc
              com.docker.lb.port: 80
        networks:
            - coin_ingress
    api:
        image: dtr.r0b.cc/engineering/tempapi:1.0
        deploy:
           labels:
             com.docker.lb.hosts: api.coin.r0b.cc
             com.docker.lb.port: 8082
        networks:
            - coin_ingress

    hasher:
        image: dtr.r0b.cc/engineering/hasher:1.0
        deploy:
            mode: replicated
            replicas: 2
        networks:
            - coin_ingress

    redis:
        image: dtr.r0b.cc/engineering/redis-cont:1.0
        networks:
            - coin_ingress

networks:
    coin_ingress:
       driver: overlay
       ipam:
           driver: default
           config:
              - subnet: 192.168.20.0/16
